---
- name: Create entrypoint directory
  ansible.builtin.file:
    mode: 0777
    path: /entrypoint
    state: directory

- name: Copy entrypoint files
  ansible.builtin.copy:
    mode: 0777
    path: /entrypoint/
    src: "{{ item }}"
  with_fileglob:
    - entrypoint/*py
