---
# tasks file for install Jupyter
- include_tasks: OS-Family-Debian.yml
  when: ansible_os_family == "Debian"

- name: Install Python3 and Pip3 if does not exists
  package:
    name:
      - python3-pip
    state: present

- name: Install Jupyter Notebook
  pip:
    name:
      - jupyter
    executable: pip3
    state: forcereinstall
  vars:
    ansible_python_interpreter: /usr/bin/python3

- include_tasks: Container-Image-Entrypoint.yml
  when: (container_iamge_builder)
